import { getChatGPTUser } from "../../chatgpt-auth";
import { createRecipients, listDeliveryDetail, revokeRecipient } from "../../../db/delivery-store";
import { requireWorkspaceRole } from "../../../db/member-store";
import { issueQuote } from "../../../db/quote-store";

export const dynamic = "force-dynamic";
const TENANT_ID = "finance-advisory-partners";
export async function GET(request: Request) { const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Sign in with ChatGPT to view delivery tracking." }, { status: 401 }); try { await requireWorkspaceRole(TENANT_ID, user, ["owner", "admin", "quoter"]); const reference = new URL(request.url).searchParams.get("reference"); if (!reference) return Response.json({ error: "Quote reference is required." }, { status: 400 }); return Response.json(await listDeliveryDetail(TENANT_ID, reference)); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Delivery tracking is unavailable." }, { status: 403 }); } }
export async function POST(request: Request) { const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Sign in with ChatGPT to send quotes." }, { status: 401 }); try { await requireWorkspaceRole(TENANT_ID, user, ["owner", "admin", "quoter"]); const body = (await request.json()) as { reference?: string; recipients?: Array<{ name: string; email: string }>; message?: string }; if (!body.reference || !body.recipients?.length) return Response.json({ error: "Quote reference and at least one recipient are required." }, { status: 400 }); await issueQuote(TENANT_ID, body.reference, user.email); const recipients = await createRecipients(TENANT_ID, body.reference, body.recipients.slice(0, 10), user.email); return Response.json({ recipients: recipients.map((recipient) => ({ ...recipient, path: `/q/${recipient.token}` })), warning: "Delivery uses the platform outbox until a verified sending domain is connected." }, { status: 202 }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "The quote could not be sent." }, { status: 409 }); } }
export async function PATCH(request: Request) { const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Sign in with ChatGPT to manage recipient links." }, { status: 401 }); try { await requireWorkspaceRole(TENANT_ID, user, ["owner", "admin", "quoter"]); const body = (await request.json()) as { action?: "revoke" | "resend"; recipientId?: string; reference?: string; name?: string; email?: string }; if (body.action === "revoke" && body.recipientId) await revokeRecipient(TENANT_ID, body.recipientId); else if (body.action === "resend" && body.reference && body.name && body.email) await createRecipients(TENANT_ID, body.reference, [{ name: body.name, email: body.email }], user.email); else return Response.json({ error: "A supported recipient action is required." }, { status: 400 }); return Response.json({ ok: true }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "The recipient link could not be updated." }, { status: 409 }); } }
