import { getCurrentUser } from "../../auth";
import { createRecipients, exportRecipientEvents, listDeliveryDetail, revokeRecipient, deleteRecipientEvents, sendRecipientReminder, type RecipientInput } from "../../../db/delivery-store";
import { requireWorkspaceContext } from "../../../db/workspace-store";
import { issueQuote } from "../../../db/quote-store";
import { assertCapacity } from "../../../db/entitlement-store";
export const dynamic="force-dynamic";
export async function GET(request:Request){const user=await getCurrentUser();if(!user)return Response.json({error:"Sign in to QuoteBench to view delivery tracking."},{status:401});try{const context=await requireWorkspaceContext(user,["owner","admin","quoter"]);const url=new URL(request.url);const reference=url.searchParams.get("reference");const recipientId=url.searchParams.get("recipientId");if(url.searchParams.get("export")==="recipient"&&recipientId)return Response.json(await exportRecipientEvents(context.tenantId,recipientId));if(!reference)return Response.json({error:"Quote reference is required."},{status:400});return Response.json(await listDeliveryDetail(context.tenantId,reference));}catch(error){return Response.json({error:error instanceof Error?error.message:"Delivery tracking is unavailable."},{status:403});}}
export async function POST(request:Request){const user=await getCurrentUser();if(!user)return Response.json({error:"Sign in to QuoteBench to send quotes."},{status:401});try{const context=await requireWorkspaceContext(user,["owner","admin","quoter"]);const body=await request.json()as{reference?:string;recipients?:RecipientInput[];message?:string};if(!body.reference||!body.recipients?.length)return Response.json({error:"Quote reference and at least one recipient are required."},{status:400});if(!body.recipients.some(recipient=>recipient.signatureRequired!==false&&recipient.role!=="viewer"))return Response.json({error:"At least one required signatory is needed."},{status:400});await assertCapacity(context.tenantId,"emails",body.recipients.slice(0,20).length);await issueQuote(context.tenantId,body.reference,user.email);const recipients=await createRecipients(context.tenantId,body.reference,body.recipients.slice(0,20),user.email,new URL(request.url).origin,body.message);const queued=recipients.filter(recipient=>recipient.status==="Queued").length;return Response.json({recipients:recipients.map(recipient=>({...recipient,path:`/q/${recipient.token}`})),warning:queued?`${queued} delivery item${queued===1?" is":"s are"} queued until the transactional email provider is configured.`:"Every recipient email was accepted by the delivery provider."},{status:202});}catch(error){return Response.json({error:error instanceof Error?error.message:"The quote could not be sent."},{status:409});}}
export async function PATCH(request:Request){const user=await getCurrentUser();if(!user)return Response.json({error:"Sign in to QuoteBench to manage recipient links."},{status:401});try{const context=await requireWorkspaceContext(user,["owner","admin","quoter"]);const body=await request.json()as{action?:"revoke"|"resend"|"remind"|"delete_events";recipientId?:string;reference?:string;name?:string;email?:string;role?:RecipientInput["role"];signingOrder?:number;signatureRequired?:boolean;reminderIntervalDays?:number;expiresAt?:string|null};if(body.action==="revoke"&&body.recipientId)await revokeRecipient(context.tenantId,body.recipientId);else if(body.action==="remind"&&body.recipientId){await assertCapacity(context.tenantId,"emails");await sendRecipientReminder(context.tenantId,body.recipientId,user.email,new URL(request.url).origin);}else if(body.action==="resend"&&body.reference&&body.name&&body.email){await assertCapacity(context.tenantId,"emails");await createRecipients(context.tenantId,body.reference,[body as RecipientInput],user.email,new URL(request.url).origin);}else if(body.action==="delete_events"&&body.recipientId)await deleteRecipientEvents(context.tenantId,body.recipientId,user.email);else return Response.json({error:"A supported recipient action is required."},{status:400});return Response.json({ok:true});}catch(error){return Response.json({error:error instanceof Error?error.message:"The recipient link could not be updated."},{status:409});}}
