import { getChatGPTUser } from "../../chatgpt-auth";
import { completePdfJob, createPdfJob, failPdfJob, getPdfJob } from "../../../db/document-store";
import { requireWorkspaceRole } from "../../../db/member-store";
import { getInternalQuote } from "../../../db/quote-store";

export const dynamic = "force-dynamic";
const TENANT_ID = "finance-advisory-partners";

function pdfEscape(value: string) { return value.replaceAll("\\", "\\\\").replaceAll("(", "\\(").replaceAll(")", "\\)").replace(/[^\x20-\x7E]/g, "?"); }
function simplePdf(lines: string[]) { const content = lines.slice(0, 42).map((line, index) => `BT /F1 ${index === 0 ? 18 : 10} Tf 54 ${780 - index * 17} Td (${pdfEscape(line)}) Tj ET`).join("\n"); const objects = ["1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj", "2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj", "3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >> endobj", `4 0 obj << /Length ${content.length} >> stream\n${content}\nendstream endobj`, "5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj"]; let pdf = "%PDF-1.4\n"; const offsets = [0]; for (const object of objects) { offsets.push(pdf.length); pdf += `${object}\n`; } const xref = pdf.length; pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, "0")} 00000 n `).join("\n")}\ntrailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`; return new TextEncoder().encode(pdf); }

export async function POST(request: Request) { const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Sign in with ChatGPT to generate PDFs." }, { status: 401 }); try { await requireWorkspaceRole(TENANT_ID, user, ["owner", "admin", "quoter"]); const body = (await request.json()) as { reference?: string }; if (!body.reference) return Response.json({ error: "Quote reference is required." }, { status: 400 }); const quote = await getInternalQuote(TENANT_ID, body.reference); if (!quote) return Response.json({ error: "Quote not found." }, { status: 404 }); return Response.json({ job: await createPdfJob(TENANT_ID, body.reference, user.email) }, { status: 202 }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "PDF generation could not be queued." }, { status: 409 }); } }
export async function GET(request: Request) { const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Sign in with ChatGPT to access PDFs." }, { status: 401 }); try { await requireWorkspaceRole(TENANT_ID, user, ["owner", "admin", "quoter"]); const id = new URL(request.url).searchParams.get("id"); if (!id) return Response.json({ error: "Job ID is required." }, { status: 400 }); let job = await getPdfJob(TENANT_ID, id); if (!job) return Response.json({ error: "PDF job not found." }, { status: 404 }); if (job.status === "Queued") { try { const quote = await getInternalQuote(TENANT_ID, String(job.quote_reference)); if (!quote) throw new Error("Quote not found."); const bytes = simplePdf([`QuoteBench proposal ${quote.reference}`, `Prepared for ${quote.clientName}`, `Contact: ${quote.contactName}`, `Valid until ${quote.validUntil}`, `One-off total: GBP ${(quote.oneOffTotalMinor / 100).toFixed(2)}`, `Annualised recurring: GBP ${(quote.recurringAnnualisedMinor / 100).toFixed(2)}`, "", quote.document.title, quote.document.introduction, quote.document.scopeHeading]); await completePdfJob(TENANT_ID, id, quote.reference, user.email, bytes); } catch (error) { await failPdfJob(TENANT_ID, id, error instanceof Error ? error.message : "Generation failed."); } job = await getPdfJob(TENANT_ID, id); } return Response.json({ job, downloadPath: job?.file_id ? `/api/files/${job.file_id}` : null }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "PDF status is unavailable." }, { status: 500 }); } }
