import { getChatGPTUser } from "../../chatgpt-auth";
import { AI_FEATURES, getAiConfig, runAiAssist, saveAiConfig, type AiFeature } from "../../../db/ai-store";
import { auditSecurity, enforceRateLimit, requireWorkspaceContext } from "../../../db/workspace-store";

export const dynamic = "force-dynamic";
export async function GET() { const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Sign in with ChatGPT to access AI assistance." }, { status: 401 }); try { const context = await requireWorkspaceContext(user, ["owner", "admin", "quoter"]); return Response.json({ config: await getAiConfig(context.tenantId), features: AI_FEATURES }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "AI assistance is unavailable." }, { status: 403 }); } }
export async function POST(request: Request) { const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Sign in with ChatGPT to use AI assistance." }, { status: 401 }); try { const body = await request.json() as { action?: "configure" | "assist"; providerName?: string; endpointUrl?: string; model?: string; apiKey?: string; enabledFeatures?: string[]; feature?: AiFeature; context?: string };
  if (body.action === "configure") { const workspace = await requireWorkspaceContext(user, ["owner", "admin"]); const config = await saveAiConfig(workspace.tenantId, user.email, { providerName: body.providerName ?? "", endpointUrl: body.endpointUrl ?? "", model: body.model ?? "", apiKey: body.apiKey, enabledFeatures: body.enabledFeatures ?? [] }); await auditSecurity({ tenantId: workspace.tenantId, actorEmail: user.email, eventType: "ai.provider_configured", resourceType: "ai_provider", resourceId: config.providerName, outcome: "success", details: { endpointHost: new URL(config.endpointUrl).hostname, model: config.model, features: config.enabledFeatures } }); return Response.json({ config }); }
  const workspace = await requireWorkspaceContext(user, ["owner", "admin", "quoter"]); const feature = body.feature as AiFeature; const rate = await enforceRateLimit(`ai:${workspace.tenantId}:${user.email}`, 30, 3600); if (!rate.allowed) return Response.json({ error: "Workspace AI assistance limit reached for this hour." }, { status: 429 }); const output = await runAiAssist(workspace.tenantId, feature, body.context ?? ""); await auditSecurity({ tenantId: workspace.tenantId, actorEmail: user.email, eventType: "ai.assistance_generated", resourceType: "ai_feature", resourceId: feature, outcome: "success", details: { inputCharacters: String(body.context ?? "").length, outputCharacters: output.length, humanApprovalRequired: true } }); return Response.json({ output, humanApprovalRequired: true });
} catch (error) { return Response.json({ error: error instanceof Error ? error.message : "AI assistance failed." }, { status: 409 }); } }
