"use client";
import { useEffect, useState } from "react";

type Workspace = { redeemedCodes: number; lifetimeTier: number; lifetimePlan: string | null; subscription: Record<string, unknown> | null; effectivePlan: string; limits: Record<string, number>; checkoutConfigured: boolean; portalConfigured: boolean; accessActive: boolean; override: Record<string, unknown> | null };
const plans = [{ name: "Starter", price: "£49", summary: "Structured quoting for small commercial teams." }, { name: "Professional", price: "£149", summary: "Governed CPQ, proposals, signatures and integrations." }, { name: "Scale", price: "£399", summary: "Higher-volume controls for larger multi-user practices." }] as const;

export default function BillingScreen() {
  const [workspace, setWorkspace] = useState<Workspace | null>(null); const [code, setCode] = useState(""); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  function load() { fetch("/api/billing", { cache: "no-store" }).then(async response => { const payload = await response.json() as Workspace & { error?: string }; if (!response.ok) throw new Error(payload.error); setWorkspace(payload); }).catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Billing is unavailable.")); }
  useEffect(load, []);
  async function act(action: string, input: Record<string, string> = {}) { setBusy(true); setMessage(null); try { const response = await fetch("/api/billing", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, ...input, returnUrl: window.location.href.split("?")[0] }) }); const payload = await response.json() as Workspace & { url?: string; error?: string }; if (!response.ok) throw new Error(payload.error); if (payload.url) { window.location.assign(payload.url); return; } setWorkspace(payload); setMessage("The entitlement was updated successfully."); } catch (error) { setMessage(error instanceof Error ? error.message : "Billing could not be changed."); } finally { setBusy(false); } }
  return <div className="standard-page"><div className="page-heading"><div><p className="eyebrow">Commercial administration</p><h1>Plans and billing</h1><p className="page-subtitle">Manage contracted subscriptions, lifetime entitlements and effective resource limits from one governed record.</p></div><span className="status">{workspace?.effectivePlan ?? "Loading"}</span></div>{message && <div className="notice" role="status"><span>i</span>{message}<button onClick={() => setMessage(null)}>×</button></div>}
    {workspace?.override && <div className="delivery-warning"><strong>Operator entitlement override active</strong><p>The platform administrator has applied a controlled entitlement exception. Contact support if the plan or expiry is unexpected.</p></div>}
    <div className="billing-plan-grid">{plans.map(plan => <section className={`billing-plan-card ${workspace?.effectivePlan === plan.name ? "current" : ""}`} key={plan.name}><div><span>{workspace?.effectivePlan === plan.name ? "Effective plan" : "Subscription plan"}</span><h2>{plan.name}</h2><p>{plan.summary}</p></div><strong>{plan.price}<small>/month plus VAT</small></strong><button className={workspace?.effectivePlan === plan.name ? "button secondary" : "button primary"} disabled={!workspace?.checkoutConfigured || busy} onClick={() => void act("checkout", { planName: plan.name })}>{workspace?.effectivePlan === plan.name ? "Renew or update in Stripe" : `Choose ${plan.name}`}</button></section>)}</div>
    <div className="billing-grid"><section className="data-panel"><div className="panel-toolbar"><div><h2>Subscription lifecycle</h2><p>Stripe Checkout, invoices, payment recovery and cancellation remain synchronized through signed webhooks.</p></div><span className="status">{String(workspace?.subscription?.status ?? "No subscription")}</span></div><div className="subscription-card"><dl><div><dt>Stripe plan</dt><dd>{String(workspace?.subscription?.plan_name ?? "None")}</dd></div><div><dt>Period end</dt><dd>{workspace?.subscription?.current_period_end ? new Date(String(workspace.subscription.current_period_end)).toLocaleDateString("en-GB") : "Not available"}</dd></div><div><dt>Payment failure</dt><dd>{workspace?.subscription?.payment_failure_at ? new Date(String(workspace.subscription.payment_failure_at)).toLocaleDateString("en-GB") : "None"}</dd></div></dl><button className="button secondary" disabled={!workspace?.subscription || !workspace?.portalConfigured || busy} onClick={() => void act("portal")}>Manage payment method, invoices or cancellation</button></div></section><section className="data-panel"><div className="panel-toolbar"><div><h2>Lifetime deal</h2><p>Each valid unused code adds one tier. The most generous contracted or lifetime entitlement applies.</p></div></div><div className="deal-redemption"><input value={code} onChange={event => setCode(event.target.value.toUpperCase())} placeholder="Enter deal code"/><button className="button primary" disabled={!code.trim() || busy} onClick={() => void act("redeem", { code })}>Redeem and stack</button></div><div className="billing-summary"><span>Codes redeemed<strong>{workspace?.redeemedCodes ?? 0}</strong></span><span>Lifetime tier<strong>{workspace?.lifetimeTier ?? 0}</strong></span><span>Lifetime plan<strong>{workspace?.lifetimePlan ?? "None"}</strong></span></div></section></div>
    <section className="data-panel plan-comparison"><div className="panel-toolbar"><div><h2>Effective limits</h2><p>Every chargeable resource uses these limits and the same 10% controlled grace band.</p></div><span className="status">{workspace?.accessActive === false ? "Read and export" : "Creation active"}</span></div><div className="plan-limits">{Object.entries(workspace?.limits ?? {}).map(([key, value]) => <span key={key}><small>{key}</small><strong>{key === "storage" ? `${(value / 1_000_000).toLocaleString()} MB` : value.toLocaleString()}</strong></span>)}</div></section>
  </div>;
}
