"use client";

import { useMemo, useState } from "react";
import type { CatalogueItem, Frequency, PricingBasis } from "../packages/pricing-engine/src/index";
import type { ProposalType, ServiceCategory } from "../db/catalogue-store";
import { formatMoney, localeForCurrency } from "../lib/market";

const frequencyLabels: Record<Frequency, string> = { one_off: "One-off", weekly: "Weekly", fortnightly: "Fortnightly", monthly: "Monthly", quarterly: "Quarterly", annually: "Annually" };
const pricingLabels: Record<PricingBasis, string> = { fixed: "Fixed", per_unit: "Per unit", cost_plus: "Cost plus", retainer: "Retainer", usage: "Usage" };
const money = (value: number, currency = "GBP") => formatMoney(value,currency,localeForCurrency(currency));

type ServiceForm = {
  name: string; categoryId: string; subcategoryId: string; description: string; serviceSchedule: string; serviceTerms: string;
  unitLabel: string; pricingBasis: PricingBasis; recurrence: Frequency; baseCurrency: string; basePrice: string; cost: string; targetMargin: string;
  minQuantity: string; maxQuantity: string; proposalTypeIds: string[]; defaultProposalTypeIds: string[];
  bundleItemIds: string[]; optionalUpgradeItemIds: string[]; requiredItemIds: string[]; incompatibleItemIds: string[];
  volumeTiers: string; regionalPrices: string; taxCode: string; taxRate: string; pricesIncludeTax: boolean;
  includedUnits: string; overagePrice: string; minimumCommitment: string; indexationMethod: "fixed" | "cpi" | "rpi" | "custom"; indexationRate: string; indexationBaseDate: string; indexationInterval: string;
};

const emptyService = (categoryId = ""): ServiceForm => ({ name: "", categoryId, subcategoryId: "", description: "", serviceSchedule: "", serviceTerms: "", unitLabel: "unit", pricingBasis: "fixed", recurrence: "one_off", baseCurrency: "GBP", basePrice: "0", cost: "0", targetMargin: "40", minQuantity: "1", maxQuantity: "", proposalTypeIds: [], defaultProposalTypeIds: [], bundleItemIds: [], optionalUpgradeItemIds: [], requiredItemIds: [], incompatibleItemIds: [], volumeTiers: "", regionalPrices: "", taxCode: "STANDARD", taxRate: "20", pricesIncludeTax: false, includedUnits: "0", overagePrice: "0", minimumCommitment: "0", indexationMethod: "fixed", indexationRate: "0", indexationBaseDate: new Date().toISOString().slice(0, 10), indexationInterval: "12" });
function toggle(values: string[], id: string) { return values.includes(id) ? values.filter(value => value !== id) : [...values, id]; }
function parseVolumeTiers(value: string) { return value.split("\n").map(line => line.trim()).filter(Boolean).map(line => { const [range, price] = line.split(":"); const [from, to] = range.split("-"); return { fromQuantity: Number(from), ...(to ? { toQuantity: Number(to) } : {}), unitPriceMinor: Math.round(Number(price) * 100) }; }); }
function parseRegionalPrices(value: string) { return value.split("\n").map(line => line.trim()).filter(Boolean).map(line => { const [regionCode, currency, price] = line.split(",").map(part => part.trim()); return { regionCode: regionCode.toUpperCase(), currency: currency.toUpperCase(), unitPriceMinor: Math.round(Number(price) * 100) }; }); }
function formatVolumeTiers(item?: CatalogueItem) { return (item?.volumeTiers ?? []).map(tier => `${tier.fromQuantity}${tier.toQuantity ? `-${tier.toQuantity}` : ""}:${Number(tier.unitPriceMinor) / 100}`).join("\n"); }
function formatRegionalPrices(item?: CatalogueItem) { return (item?.regionalPrices ?? []).map(entry => `${entry.regionCode},${entry.currency},${Number(entry.unitPriceMinor) / 100}`).join("\n"); }

export default function CatalogueScreen({ catalogueItems, categories, proposalTypes, onRefresh }: { catalogueItems: CatalogueItem[]; categories: ServiceCategory[]; proposalTypes: ProposalType[]; onRefresh: () => Promise<void> }) {
  const [tab, setTab] = useState<"services" | "categories" | "proposal_types">("services");
  const [search, setSearch] = useState(""); const [editingService, setEditingService] = useState<CatalogueItem | null>(null); const [service, setService] = useState<ServiceForm>(emptyService());
  const [category, setCategory] = useState({ id: "", name: "", parentId: "", sortOrder: "0", active: true }); const [proposalType, setProposalType] = useState({ id: "", name: "", description: "", active: true });
  const [editorOpen, setEditorOpen] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const topCategories = categories.filter(item => !item.parentId); const activeTypes = proposalTypes.filter(type => type.active); const eligibleRelationships = catalogueItems.filter(item => item.id !== editingService?.id);
  const grouped = useMemo(() => { const query = search.trim().toLowerCase(); const visible = catalogueItems.filter(item => !query || `${item.name} ${item.description ?? ""}`.toLowerCase().includes(query)); return topCategories.map(parent => ({ parent, items: visible.filter(item => item.categoryId === parent.id) })).filter(group => group.items.length); }, [catalogueItems, search, topCategories]);

  function openService(item?: CatalogueItem) {
    setEditingService(item ?? null);
    setService(item ? { ...emptyService(item.categoryId), name: item.name, categoryId: item.categoryId, subcategoryId: item.subcategoryId ?? "", description: item.description ?? "", serviceSchedule: item.serviceSchedule ?? "", serviceTerms: item.serviceTerms ?? "", unitLabel: item.unitLabel, pricingBasis: item.pricingBasis, recurrence: item.recurrence, baseCurrency: item.baseCurrency ?? "GBP", basePrice: String(Number(item.basePriceMinor ?? 0) / 100), cost: String(Number(item.costMinor ?? 0) / 100), targetMargin: String(Number(item.targetMarginBp ?? 4000) / 100), minQuantity: String(item.minQuantity ?? 1), maxQuantity: item.maxQuantity ? String(item.maxQuantity) : "", proposalTypeIds: item.proposalTypeIds ?? [], defaultProposalTypeIds: item.defaultProposalTypeIds ?? [], bundleItemIds: item.bundleItemIds ?? [], optionalUpgradeItemIds: item.optionalUpgradeItemIds ?? [], requiredItemIds: item.requiredItemIds ?? [], incompatibleItemIds: item.incompatibleItemIds ?? [], volumeTiers: formatVolumeTiers(item), regionalPrices: formatRegionalPrices(item), taxCode: item.taxCode ?? "STANDARD", taxRate: String(Number(item.taxRateBp ?? 0) / 100), pricesIncludeTax: item.pricesIncludeTax ?? false, includedUnits: String(item.includedUnits ?? 0), overagePrice: String(Number(item.overagePriceMinor ?? 0) / 100), minimumCommitment: String(Number(item.minimumCommitmentMinor ?? 0) / 100), indexationMethod: item.indexation?.method ?? "fixed", indexationRate: String(Number(item.indexation?.annualRateBp ?? 0) / 100), indexationBaseDate: item.indexation?.baseDate ?? new Date().toISOString().slice(0, 10), indexationInterval: String(item.indexation?.intervalMonths ?? 12) } : emptyService(topCategories[0]?.id));
    setTab("services"); setMessage(null); setEditorOpen(true);
  }
  async function post(body: Record<string, unknown>) { setSaving(true); setMessage(null); try { const response = await fetch("/api/catalogue", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error ?? "The commercial configuration could not be saved."); await onRefresh(); setEditorOpen(false); } catch (error) { setMessage(error instanceof Error ? error.message : "The commercial configuration could not be saved."); } finally { setSaving(false); } }
  async function saveService() { await post({ id: editingService?.id ?? service.name, name: service.name, categoryId: service.categoryId, subcategoryId: service.subcategoryId || undefined, description: service.description, serviceSchedule: service.serviceSchedule, serviceTerms: service.serviceTerms, unitLabel: service.unitLabel, pricingBasis: service.pricingBasis, recurrence: service.recurrence, baseCurrency: service.baseCurrency.toUpperCase(), basePriceMinor: Math.round(Number(service.basePrice) * 100), costMinor: Number(service.cost) > 0 ? Math.round(Number(service.cost) * 100) : undefined, targetMarginBp: Math.round(Number(service.targetMargin) * 100), minQuantity: Number(service.minQuantity), maxQuantity: service.maxQuantity ? Number(service.maxQuantity) : undefined, proposalTypeIds: service.proposalTypeIds, defaultProposalTypeIds: service.defaultProposalTypeIds, bundleItemIds: service.bundleItemIds, optionalUpgradeItemIds: service.optionalUpgradeItemIds, requiredItemIds: service.requiredItemIds, incompatibleItemIds: service.incompatibleItemIds, volumeTiers: parseVolumeTiers(service.volumeTiers), regionalPrices: parseRegionalPrices(service.regionalPrices), taxCode: service.taxCode, taxRateBp: Math.round(Number(service.taxRate) * 100), pricesIncludeTax: service.pricesIncludeTax, includedUnits: Number(service.includedUnits), overagePriceMinor: Math.round(Number(service.overagePrice) * 100), minimumCommitmentMinor: Math.round(Number(service.minimumCommitment) * 100), indexation: { method: service.indexationMethod, annualRateBp: Math.round(Number(service.indexationRate) * 100), baseDate: service.indexationBaseDate, intervalMonths: Number(service.indexationInterval) } }); }

  return <div className="standard-page">
    <div className="page-heading"><div><p className="eyebrow">Commercial configuration engine</p><h1>Services and CPQ</h1><p className="page-subtitle">Govern bundles, dependencies, price tiers, usage, retainers, tax, currencies and indexation from one catalogue.</p></div><button className="button primary" onClick={() => tab === "services" ? openService() : (setEditorOpen(true), setMessage(null))}>+ {tab === "services" ? "Add service" : tab === "categories" ? "Add category" : "Add proposal type"}</button></div>
    <div className="catalogue-tabs"><button className={tab === "services" ? "active" : ""} onClick={() => { setTab("services"); setEditorOpen(false); }}>Services</button><button className={tab === "categories" ? "active" : ""} onClick={() => { setTab("categories"); setEditorOpen(false); }}>Categories</button><button className={tab === "proposal_types" ? "active" : ""} onClick={() => { setTab("proposal_types"); setEditorOpen(false); }}>Proposal types</button></div>
    {editorOpen && tab === "services" && <section className="catalogue-editor service-editor advanced-cpq-editor">
      <div className="editor-heading"><div><p className="eyebrow">{editingService ? "Edit commercial component" : "New commercial component"}</p><h2>{editingService?.name ?? "Service definition"}</h2></div><button aria-label="Close service editor" onClick={() => setEditorOpen(false)}>×</button></div>
      <h3>Core service</h3><div className="editor-grid service-core-grid">
        <label><span>Name</span><input value={service.name} onChange={event => setService({ ...service, name: event.target.value })} /></label><label><span>Category</span><select value={service.categoryId} onChange={event => setService({ ...service, categoryId: event.target.value, subcategoryId: "" })}>{topCategories.filter(item => item.active).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Subcategory</span><select value={service.subcategoryId} onChange={event => setService({ ...service, subcategoryId: event.target.value })}><option value="">No subcategory</option>{categories.filter(item => item.parentId === service.categoryId && item.active).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Unit</span><input value={service.unitLabel} onChange={event => setService({ ...service, unitLabel: event.target.value })} /></label>
        <label><span>Pricing model</span><select value={service.pricingBasis} onChange={event => setService({ ...service, pricingBasis: event.target.value as PricingBasis })}>{Object.entries(pricingLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Recurrence</span><select value={service.recurrence} onChange={event => setService({ ...service, recurrence: event.target.value as Frequency })}>{Object.entries(frequencyLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Base currency</span><input maxLength={3} value={service.baseCurrency} onChange={event => setService({ ...service, baseCurrency: event.target.value.toUpperCase() })} /></label><label><span>Base price</span><input type="number" min="0" step="0.01" value={service.basePrice} onChange={event => setService({ ...service, basePrice: event.target.value })} /></label><label><span>Cost</span><input type="number" min="0" step="0.01" value={service.cost} onChange={event => setService({ ...service, cost: event.target.value })} /></label>{service.pricingBasis === "cost_plus" && <label><span>Target margin (%)</span><input type="number" value={service.targetMargin} onChange={event => setService({ ...service, targetMargin: event.target.value })} /></label>}<label><span>Minimum quantity</span><input type="number" min="1" value={service.minQuantity} onChange={event => setService({ ...service, minQuantity: event.target.value })} /></label><label><span>Maximum quantity</span><input type="number" min="1" value={service.maxQuantity} placeholder="No limit" onChange={event => setService({ ...service, maxQuantity: event.target.value })} /></label>
      </div>
      <div className="service-copy-grid"><label><span>Short description</span><textarea value={service.description} onChange={event => setService({ ...service, description: event.target.value })} /></label><label><span>Service schedule</span><textarea value={service.serviceSchedule} onChange={event => setService({ ...service, serviceSchedule: event.target.value })} /></label><label><span>Service-specific terms</span><textarea value={service.serviceTerms} onChange={event => setService({ ...service, serviceTerms: event.target.value })} /></label></div>
      <h3>Bundles and configuration rules</h3><div className="cpq-relationship-grid">{eligibleRelationships.map(item => <div key={item.id}><strong>{item.name}</strong><label><input type="checkbox" checked={service.bundleItemIds.includes(item.id)} onChange={() => setService({ ...service, bundleItemIds: toggle(service.bundleItemIds, item.id) })} /> Bundle component</label><label><input type="checkbox" checked={service.optionalUpgradeItemIds.includes(item.id)} onChange={() => setService({ ...service, optionalUpgradeItemIds: toggle(service.optionalUpgradeItemIds, item.id) })} /> Optional upgrade</label><label><input type="checkbox" checked={service.requiredItemIds.includes(item.id)} onChange={() => setService({ ...service, requiredItemIds: toggle(service.requiredItemIds, item.id) })} /> Required dependency</label><label><input type="checkbox" checked={service.incompatibleItemIds.includes(item.id)} onChange={() => setService({ ...service, incompatibleItemIds: toggle(service.incompatibleItemIds, item.id) })} /> Incompatible</label></div>)}</div>
      <h3>Tiered, regional and recurring economics</h3><div className="cpq-economics-grid"><label><span>Volume tiers</span><small>One per line: 1-10:250 or 11-:200</small><textarea rows={5} value={service.volumeTiers} onChange={event => setService({ ...service, volumeTiers: event.target.value })} /></label><label><span>Regional and currency prices</span><small>One per line: UK,GBP,500 or GLOBAL,USD,650</small><textarea rows={5} value={service.regionalPrices} onChange={event => setService({ ...service, regionalPrices: event.target.value })} /></label><div className="editor-grid"><label><span>Included usage units</span><input type="number" min="0" value={service.includedUnits} onChange={event => setService({ ...service, includedUnits: event.target.value })} /></label><label><span>Overage price</span><input type="number" min="0" step="0.01" value={service.overagePrice} onChange={event => setService({ ...service, overagePrice: event.target.value })} /></label><label><span>Minimum commitment</span><input type="number" min="0" step="0.01" value={service.minimumCommitment} onChange={event => setService({ ...service, minimumCommitment: event.target.value })} /></label></div></div>
      <h3>Tax and price indexation</h3><div className="editor-grid"><label><span>Tax code</span><input value={service.taxCode} onChange={event => setService({ ...service, taxCode: event.target.value })} /></label><label><span>Tax rate (%)</span><input type="number" min="0" max="100" value={service.taxRate} onChange={event => setService({ ...service, taxRate: event.target.value })} /></label><label className="checkbox-field"><input type="checkbox" checked={service.pricesIncludeTax} onChange={event => setService({ ...service, pricesIncludeTax: event.target.checked })} /><span>Catalogue price includes tax</span></label><label><span>Indexation basis</span><select value={service.indexationMethod} onChange={event => setService({ ...service, indexationMethod: event.target.value as ServiceForm["indexationMethod"] })}><option value="fixed">Fixed uplift</option><option value="cpi">CPI</option><option value="rpi">RPI</option><option value="custom">Custom index</option></select></label><label><span>Annual rate (%)</span><input type="number" min="0" max="50" value={service.indexationRate} onChange={event => setService({ ...service, indexationRate: event.target.value })} /></label><label><span>Base date</span><input type="date" value={service.indexationBaseDate} onChange={event => setService({ ...service, indexationBaseDate: event.target.value })} /></label><label><span>Apply every</span><select value={service.indexationInterval} onChange={event => setService({ ...service, indexationInterval: event.target.value })}><option value="1">Month</option><option value="3">Quarter</option><option value="6">Six months</option><option value="12">Year</option><option value="24">Two years</option></select></label></div>
      <div className="proposal-type-matrix"><div><strong>Proposal-type availability</strong><p>Control availability and default selection for each commercial scenario.</p></div>{activeTypes.map(type => { const available = service.proposalTypeIds.includes(type.id); const defaultOn = service.defaultProposalTypeIds.includes(type.id); return <div key={type.id}><span><strong>{type.name}</strong><small>{type.description}</small></span><label><input type="checkbox" checked={available} onChange={() => setService(current => ({ ...current, proposalTypeIds: toggle(current.proposalTypeIds, type.id), defaultProposalTypeIds: available ? current.defaultProposalTypeIds.filter(id => id !== type.id) : current.defaultProposalTypeIds }))} /> Available</label><label><input type="checkbox" checked={defaultOn} disabled={!available} onChange={() => setService(current => ({ ...current, defaultProposalTypeIds: toggle(current.defaultProposalTypeIds, type.id) }))} /> Default on</label></div>; })}</div>
      {message && <p className="editor-error">{message}</p>}<div className="editor-actions"><button className="button secondary" onClick={() => setEditorOpen(false)}>Cancel</button><button className="button primary" onClick={() => void saveService()} disabled={saving || !service.name.trim() || !service.categoryId}>{saving ? "Saving…" : "Save commercial component"}</button></div>
    </section>}
    {editorOpen && tab === "categories" && <section className="catalogue-editor"><div className="editor-heading"><h2>Category</h2><button onClick={() => setEditorOpen(false)}>×</button></div><div className="editor-grid"><label><span>Name</span><input value={category.name} onChange={event => setCategory({ ...category, name: event.target.value })} /></label><label><span>Parent category</span><select value={category.parentId} onChange={event => setCategory({ ...category, parentId: event.target.value })}><option value="">Top level</option>{topCategories.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Sort order</span><input type="number" value={category.sortOrder} onChange={event => setCategory({ ...category, sortOrder: event.target.value })} /></label></div><div className="editor-actions"><button className="button primary" onClick={() => void post({ action: "upsert_category", ...category, sortOrder: Number(category.sortOrder) })} disabled={!category.name.trim() || saving}>Save category</button></div></section>}
    {editorOpen && tab === "proposal_types" && <section className="catalogue-editor"><div className="editor-heading"><h2>Proposal type</h2><button onClick={() => setEditorOpen(false)}>×</button></div><label><span>Name</span><input value={proposalType.name} onChange={event => setProposalType({ ...proposalType, name: event.target.value })} /></label><label><span>Description</span><textarea value={proposalType.description} onChange={event => setProposalType({ ...proposalType, description: event.target.value })} /></label><div className="editor-actions"><button className="button primary" onClick={() => void post({ action: "upsert_proposal_type", ...proposalType })} disabled={!proposalType.name.trim() || saving}>Save proposal type</button></div></section>}
    {tab === "services" && <section className="data-panel"><div className="panel-toolbar"><div><h2>Service catalogue</h2><p>{catalogueItems.length} governed commercial components</p></div><input placeholder="Search services" value={search} onChange={event => setSearch(event.target.value)} /></div><div className="service-catalogue-list">{grouped.map(group => <section key={group.parent.id}><header><span>{group.parent.name.charAt(0)}</span><div><h3>{group.parent.name}</h3><p>{group.items.length} configured services</p></div></header><div className="service-subgroup">{group.items.map(item => <button key={item.id} onClick={() => openService(item)}><span><strong>{item.name}</strong><small>{item.description || "No description supplied"}</small></span><span>{pricingLabels[item.pricingBasis]}</span><span>{money(Number(item.basePriceMinor ?? item.costMinor ?? 0), item.baseCurrency)}</span><span>{item.bundleItemIds?.length ? `${item.bundleItemIds.length} bundle items` : `${item.proposalTypeIds?.length ?? 0} proposal types`}</span><span>{item.indexation?.annualRateBp ? `${Number(item.indexation.annualRateBp) / 100}% indexation` : "No indexation"}</span><b>›</b></button>)}</div></section>)}</div></section>}
    {tab === "categories" && <section className="data-panel"><div className="panel-toolbar"><h2>Category hierarchy</h2></div>{categories.map(item => <button className="governance-row" key={item.id} onClick={() => { setCategory({ id: item.id, name: item.name, parentId: item.parentId ?? "", sortOrder: String(item.sortOrder), active: item.active }); setEditorOpen(true); }}><strong>{item.parentId ? "↳ " : ""}{item.name}</strong><span>{item.active ? "Active" : "Inactive"}</span></button>)}</section>}
    {tab === "proposal_types" && <section className="data-panel"><div className="panel-toolbar"><h2>Proposal configurations</h2></div>{proposalTypes.map(item => <button className="governance-row" key={item.id} onClick={() => { setProposalType({ id: item.id, name: item.name, description: item.description, active: item.active }); setEditorOpen(true); }}><span><strong>{item.name}</strong><small>{item.description}</small></span><span>{item.active ? "Available" : "Inactive"}</span></button>)}</section>}
  </div>;
}

