"use client";

import { useEffect, useState } from "react";

type Governance = { tenant:{name?:string;trackingEnabled?:boolean;status?:string};securityEvents:Array<Record<string,unknown>>;retention:{trackingMonths:number;webhookLogDays:number;apiAccessLogDays:number;softDeleteDays:number} };

export default function GovernanceScreen(){
  const[data,setData]=useState<Governance|null>(null);const[message,setMessage]=useState<string|null>(null);const[confirmation,setConfirmation]=useState("");
  const load=()=>fetch("/api/governance",{cache:"no-store"}).then(async response=>{const payload=await response.json()as Governance&{error?:string};if(!response.ok)throw new Error(payload.error);setData(payload);}).catch((error:unknown)=>setMessage(error instanceof Error?error.message:"Privacy controls are unavailable."));
  useEffect(()=>{load();},[]);
  async function toggle(){const response=await fetch("/api/governance",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({trackingEnabled:!data?.tenant.trackingEnabled})});const payload=await response.json()as Governance&{error?:string};if(!response.ok){setMessage(payload.error??"Tracking preference could not be updated.");return;}setData(payload);setMessage("Tracking preference updated and recorded in the security audit log.");}
  async function remove(){if(!data?.tenant.name||confirmation!==data.tenant.name)return setMessage("Enter the exact workspace name before scheduling deletion.");const response=await fetch("/api/governance",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({confirmation})});const payload=await response.json()as{error?:string};if(!response.ok){setMessage(payload.error??"Workspace deletion could not be scheduled.");return;}setMessage("Workspace access is disabled. Purge is scheduled after the 30-day recovery window.");}
  return <div className="standard-page"><div className="page-heading"><div><p className="eyebrow">Owner-only controls</p><h1>Privacy, security & retention</h1><p className="page-subtitle">Tenant-scoped controls with auditable changes and documented retention periods.</p></div><span className="status">Security governed</span></div>{message&&<p className="storage-message">{message}</p>}<div className="metric-strip"><div><span>Engagement tracking</span><strong>{data?.tenant.trackingEnabled?"Enabled":"Disabled"}</strong></div><div><span>Tracking retention</span><strong>{data?.retention.trackingMonths??24} months</strong></div><div><span>Webhook logs</span><strong>{data?.retention.webhookLogDays??30} days</strong></div><div><span>Recovery window</span><strong>{data?.retention.softDeleteDays??30} days</strong></div></div><section className="data-panel"><div className="panel-toolbar"><div><h2>Engagement privacy</h2><p>Disable recipient-level engagement events while retaining essential proposal lifecycle records.</p></div><button className="button secondary" onClick={toggle}>{data?.tenant.trackingEnabled?"Disable tracking":"Enable tracking"}</button></div></section><section className="data-panel security-event-panel"><div className="panel-toolbar"><div><h2>Recent security events</h2><p>Boundary denials, authorisation decisions and privacy changes.</p></div></div>{data?.securityEvents.length?<div className="security-event-table"><div className="security-event-row security-event-header"><span>Event</span><span>Outcome</span><span>Actor</span><span>Recorded</span></div>{data.securityEvents.map(event=><div className="security-event-row" key={String(event.id)}><strong>{String(event.event_type)}</strong><span>{String(event.outcome)}</span><span>{String(event.actor_email??"system")}</span><span>{String(event.created_at)}</span></div>)}</div>:<p className="empty-state">No security events have been recorded for this workspace.</p>}</section><section className="data-panel governance-delete-panel"><div className="panel-toolbar"><div><h2>Delete workspace</h2><p>Access stops immediately. Durable records and objects are purged after 30 days.</p></div></div><label className="field"><span>Enter {data?.tenant.name??"the workspace name"}</span><input value={confirmation} onChange={event=>setConfirmation(event.target.value)} /></label><button className="button secondary" onClick={remove}>Schedule workspace deletion</button></section></div>;
}
