const CODE_SCHEMA=`CREATE TABLE IF NOT EXISTS deal_codes (code_hash TEXT PRIMARY KEY,tier INTEGER NOT NULL,campaign TEXT NOT NULL,redeemed_tenant_id TEXT,redeemed_at TEXT)`;
const REDEMPTION_SCHEMA=`CREATE TABLE IF NOT EXISTS deal_redemptions (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,code_hash TEXT NOT NULL,tier_contribution INTEGER NOT NULL,redeemed_by TEXT NOT NULL,redeemed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`;
const SUBSCRIPTION_SCHEMA=`CREATE TABLE IF NOT EXISTS billing_subscriptions (tenant_id TEXT PRIMARY KEY,stripe_customer_id TEXT,stripe_subscription_id TEXT,plan_name TEXT,status TEXT,current_period_end TEXT,payment_failure_at TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`;
const COHORT_SCHEMA=`CREATE TABLE IF NOT EXISTS tenant_cohorts (tenant_id TEXT PRIMARY KEY,cohort TEXT NOT NULL,lifetime_tier INTEGER NOT NULL DEFAULT 0,joined_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`;
export const PLAN_LIMITS={Starter:{clients:25,seats:2,quotes:20,pdfs:20,emails:100,storage:250_000_000},Professional:{clients:250,seats:5,quotes:100,pdfs:100,emails:1000,storage:2_000_000_000},Scale:{clients:2500,seats:20,quotes:500,pdfs:500,emails:10000,storage:10_000_000_000}} as const;
async function database(){const{env}=await import("cloudflare:workers");if(!env.DB)throw new Error("Billing storage is unavailable.");return env.DB;}
async function hash(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value.trim().toUpperCase()));return Array.from(new Uint8Array(bytes),byte=>byte.toString(16).padStart(2,"0")).join("");}
async function ensure(){const db=await database();await db.batch([db.prepare(CODE_SCHEMA),db.prepare(REDEMPTION_SCHEMA),db.prepare(SUBSCRIPTION_SCHEMA),db.prepare(COHORT_SCHEMA),db.prepare("CREATE INDEX IF NOT EXISTS deal_redemptions_tenant_idx ON deal_redemptions (tenant_id)")]);for(const [code,tier] of [["LAUNCH-ONE-2026",1],["LAUNCH-TWO-2026",1],["LAUNCH-THREE-2026",1]] as const)await db.prepare("INSERT OR IGNORE INTO deal_codes (code_hash,tier,campaign) VALUES (?,?,'2026 launch illustration')").bind(await hash(code),tier).run();return db;}
function tierPlan(tier:number){return tier>=3?"Scale":tier>=2?"Professional":tier>=1?"Starter":null;}
function planRank(plan:string|null){return plan==="Scale"?3:plan==="Professional"?2:plan==="Starter"?1:0;}
export async function getBillingWorkspace(tenantId:string){const db=await ensure();const [redeemed,subscription,cohort]=await Promise.all([db.prepare("SELECT COUNT(*) AS count,COALESCE(SUM(tier_contribution),0) AS tier FROM deal_redemptions WHERE tenant_id=?").bind(tenantId).first<{count:number;tier:number}>(),db.prepare("SELECT plan_name,status,current_period_end,payment_failure_at FROM billing_subscriptions WHERE tenant_id=?").bind(tenantId).first<Record<string,unknown>>(),db.prepare("SELECT cohort,lifetime_tier,joined_at FROM tenant_cohorts WHERE tenant_id=?").bind(tenantId).first<Record<string,unknown>>()]);const lifetimePlan=tierPlan(redeemed?.tier??0);const subscriptionPlan=subscription?.status==="active"?String(subscription.plan_name):null;const effectivePlan=planRank(lifetimePlan)>=planRank(subscriptionPlan)?lifetimePlan:subscriptionPlan;return{redeemedCodes:redeemed?.count??0,lifetimeTier:redeemed?.tier??0,lifetimePlan,subscription:subscription??null,effectivePlan:effectivePlan??"Read and export",limits:effectivePlan?PLAN_LIMITS[effectivePlan as keyof typeof PLAN_LIMITS]:null,cohort:cohort??null,checkoutConfigured:await stripeConfigured()};}
export async function redeemCode(tenantId:string,email:string,code:string){const db=await ensure();const codeHash=await hash(code);const row=await db.prepare("SELECT tier,redeemed_tenant_id FROM deal_codes WHERE code_hash=?").bind(codeHash).first<{tier:number;redeemed_tenant_id:string|null}>();if(!row)throw new Error("invalid_code");if(row.redeemed_tenant_id)throw new Error("code_already_used");await db.batch([db.prepare("UPDATE deal_codes SET redeemed_tenant_id=?,redeemed_at=CURRENT_TIMESTAMP WHERE code_hash=? AND redeemed_tenant_id IS NULL").bind(tenantId,codeHash),db.prepare("INSERT INTO deal_redemptions (id,tenant_id,code_hash,tier_contribution,redeemed_by) VALUES (?,?,?,?,?)").bind(crypto.randomUUID(),tenantId,codeHash,row.tier,email),db.prepare("INSERT INTO tenant_cohorts (tenant_id,cohort,lifetime_tier) VALUES (?,'lifetime-2026',?) ON CONFLICT(tenant_id) DO UPDATE SET cohort='lifetime-2026',lifetime_tier=lifetime_tier+excluded.lifetime_tier").bind(tenantId,row.tier)]);return getBillingWorkspace(tenantId);}
async function stripeConfigured(){const{env}=await import("cloudflare:workers");return Boolean(env.STRIPE_SECRET_KEY&&env.STRIPE_PRICE_ID);}
export async function createStripeCheckout(tenantId:string,email:string,returnUrl:string){const{env}=await import("cloudflare:workers");if(!env.STRIPE_SECRET_KEY||!env.STRIPE_PRICE_ID)throw new Error("Stripe checkout is not configured for this deployment.");const body=new URLSearchParams({mode:"subscription","line_items[0][price]":String(env.STRIPE_PRICE_ID),"line_items[0][quantity]":"1",customer_email:email,success_url:`${returnUrl}?checkout=success`,cancel_url:`${returnUrl}?checkout=cancelled`,"metadata[tenant_id]":tenantId});const response=await fetch("https://api.stripe.com/v1/checkout/sessions",{method:"POST",headers:{authorization:`Bearer ${env.STRIPE_SECRET_KEY}`,"content-type":"application/x-www-form-urlencoded"},body});const payload=await response.json() as {url?:string;error?:{message?:string}};if(!response.ok||!payload.url)throw new Error(payload.error?.message??"Stripe checkout could not be created.");return payload.url;}
export async function getOperatorCohorts(){const db=await ensure();const rows=await db.prepare(`SELECT c.tenant_id,c.cohort,c.lifetime_tier,c.joined_at,e.plan_name,e.monthly_quote_limit,(SELECT COUNT(*) FROM clients x WHERE x.tenant_id=c.tenant_id AND x.status='Active') AS active_clients,(SELECT COUNT(*) FROM workspace_members m WHERE m.tenant_id=c.tenant_id AND m.status!='Removed') AS seats,(SELECT COUNT(*) FROM quotes q WHERE q.tenant_id=c.tenant_id AND q.created_at>=datetime('now','start of month')) AS quotes_month,(SELECT COUNT(*) FROM pdf_jobs p WHERE p.tenant_id=c.tenant_id AND p.created_at>=datetime('now','start of month')) AS pdfs_month,(SELECT COUNT(*) FROM quote_recipients r WHERE r.tenant_id=c.tenant_id AND r.last_sent_at>=datetime('now','start of month')) AS emails_month,(SELECT COALESCE(SUM(size_bytes),0) FROM stored_files f WHERE f.tenant_id=c.tenant_id) AS storage_bytes FROM tenant_cohorts c LEFT JOIN workspace_entitlements e ON e.tenant_id=c.tenant_id ORDER BY c.joined_at DESC`).all<Record<string,unknown>>();return{tenants:rows.results,totals:{tenants:rows.results.length,storageBytes:rows.results.reduce((sum,row)=>sum+Number(row.storage_bytes??0),0),emailsMonth:rows.results.reduce((sum,row)=>sum+Number(row.emails_month??0),0)}};}
