export type RecipientRole = "signatory" | "approver" | "countersignatory" | "viewer";
export type Recipient = {
  id: string; quoteReference: string; name: string; email: string; token: string;
  status: "Queued" | "Delivered" | "Bounced" | "Complained" | "Revoked";
  role: RecipientRole; signingOrder: number; signatureRequired: boolean; signedAt: string | null;
  expiresAt: string | null; reminderIntervalDays: number; nextReminderAt: string | null;
  deliveredAt: string | null; firstViewedAt: string | null; lastSentAt: string | null;
};
export type RecipientInput = { name: string; email: string; role?: RecipientRole; signingOrder?: number; signatureRequired?: boolean; reminderIntervalDays?: number; expiresAt?: string | null };

const RECIPIENT_SCHEMA = `CREATE TABLE IF NOT EXISTS quote_recipients (
  id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, quote_reference TEXT NOT NULL, name TEXT NOT NULL,
  email TEXT NOT NULL, token TEXT NOT NULL UNIQUE, status TEXT NOT NULL, signer_role TEXT NOT NULL DEFAULT 'signatory',
  signing_order INTEGER NOT NULL DEFAULT 1, signature_required INTEGER NOT NULL DEFAULT 1, signed_at TEXT,
  accepted_name TEXT, signature_evidence_json TEXT, expires_at TEXT, reminder_interval_days INTEGER NOT NULL DEFAULT 3,
  next_reminder_at TEXT, reminder_count INTEGER NOT NULL DEFAULT 0, delivered_at TEXT, first_viewed_at TEXT,
  revoked_at TEXT, last_sent_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
)`;
const TRACKING_SCHEMA = `CREATE TABLE IF NOT EXISTS tracking_events (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, quote_reference TEXT NOT NULL, recipient_id TEXT, event_type TEXT NOT NULL, section TEXT, duration_ms INTEGER, device_hash TEXT, coarse_location TEXT, payload_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`;
async function database() { const { env } = await import("cloudflare:workers"); if (!env.DB) throw new Error("Delivery storage is unavailable."); return env.DB; }
async function ensureDelivery() {
  const db = await database();
  await db.batch([db.prepare(RECIPIENT_SCHEMA), db.prepare(TRACKING_SCHEMA), db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS quote_recipients_token_unique ON quote_recipients (token)"), db.prepare("CREATE INDEX IF NOT EXISTS quote_recipients_quote_idx ON quote_recipients (tenant_id, quote_reference)"), db.prepare("CREATE INDEX IF NOT EXISTS tracking_events_quote_created_idx ON tracking_events (tenant_id, quote_reference, created_at)")]);
  const additions = [
    ["signer_role", "TEXT NOT NULL DEFAULT 'signatory'"], ["signing_order", "INTEGER NOT NULL DEFAULT 1"], ["signature_required", "INTEGER NOT NULL DEFAULT 1"],
    ["signed_at", "TEXT"], ["accepted_name", "TEXT"], ["signature_evidence_json", "TEXT"], ["expires_at", "TEXT"],
    ["reminder_interval_days", "INTEGER NOT NULL DEFAULT 3"], ["next_reminder_at", "TEXT"], ["reminder_count", "INTEGER NOT NULL DEFAULT 0"],
  ] as const;
  for (const [name, definition] of additions) { try { await db.prepare(`SELECT ${name} FROM quote_recipients LIMIT 0`).run(); } catch { await db.prepare(`ALTER TABLE quote_recipients ADD COLUMN ${name} ${definition}`).run(); } }
  return db;
}

function mapRecipient(row: Record<string, unknown>): Recipient {
  return { id: String(row.id), quoteReference: String(row.quote_reference), name: String(row.name), email: String(row.email), token: String(row.token), status: row.status as Recipient["status"], role: row.signer_role as RecipientRole, signingOrder: Number(row.signing_order), signatureRequired: Number(row.signature_required) === 1, signedAt: row.signed_at ? String(row.signed_at) : null, expiresAt: row.expires_at ? String(row.expires_at) : null, reminderIntervalDays: Number(row.reminder_interval_days), nextReminderAt: row.next_reminder_at ? String(row.next_reminder_at) : null, deliveredAt: row.delivered_at ? String(row.delivered_at) : null, firstViewedAt: row.first_viewed_at ? String(row.first_viewed_at) : null, lastSentAt: row.last_sent_at ? String(row.last_sent_at) : null };
}

export async function createRecipients(tenantId: string, reference: string, recipients: RecipientInput[], actorEmail: string, origin = "", message = "Please review the attached commercial proposal.") {
  const db = await ensureDelivery(); const created: Recipient[] = [];
  for (const recipient of recipients) {
    const email = recipient.email.trim().toLowerCase(); if (!recipient.name.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) throw new Error("Every recipient requires a name and valid email address.");
    const role: RecipientRole = ["signatory", "approver", "countersignatory", "viewer"].includes(recipient.role ?? "") ? recipient.role! : "signatory";
    const required = role === "viewer" ? false : recipient.signatureRequired !== false; const order = Math.max(1, Math.min(50, Math.round(Number(recipient.signingOrder ?? 1)))); const reminder = Math.max(1, Math.min(30, Math.round(Number(recipient.reminderIntervalDays ?? 3))));
    const existing = await db.prepare("SELECT id,token FROM quote_recipients WHERE tenant_id=? AND quote_reference=? AND email=? AND status!='Revoked'").bind(tenantId, reference, email).first<{ id: string; token: string }>();
    const id = existing?.id ?? crypto.randomUUID(); const token = existing?.token ?? crypto.randomUUID().replaceAll("-", "") + crypto.randomUUID().replaceAll("-", "");
    await db.prepare(`INSERT INTO quote_recipients (id,tenant_id,quote_reference,name,email,token,status,signer_role,signing_order,signature_required,expires_at,reminder_interval_days,next_reminder_at,last_sent_at) VALUES (?,?,?,?,?,?,'Queued',?,?,?,?,?,datetime('now',? || ' days'),CURRENT_TIMESTAMP) ON CONFLICT(token) DO UPDATE SET name=excluded.name,email=excluded.email,status='Queued',signer_role=excluded.signer_role,signing_order=excluded.signing_order,signature_required=excluded.signature_required,expires_at=excluded.expires_at,reminder_interval_days=excluded.reminder_interval_days,next_reminder_at=excluded.next_reminder_at,last_sent_at=CURRENT_TIMESTAMP`).bind(id, tenantId, reference, recipient.name.trim(), email, token, role, order, required ? 1 : 0, recipient.expiresAt ?? null, reminder, `+${reminder}`).run();
    const { sendProposalDelivery } = await import("./notification-store"); const outcome = await sendProposalDelivery(tenantId, reference, { name: recipient.name.trim(), email, token }, origin, message); const status = outcome.sent ? "Delivered" : "Queued";
    await db.prepare("UPDATE quote_recipients SET status=?,delivered_at=CASE WHEN ?='Delivered' THEN CURRENT_TIMESTAMP ELSE delivered_at END WHERE id=?").bind(status, status, id).run();
    await recordTrackingEvent(token, outcome.sent ? "email_delivered" : "email_queued", null, null, null, { sender: actorEmail, provider: outcome.provider, reason: outcome.reason, role, signingOrder: order, signatureRequired: required });
    const { meterEvent } = await import("./workspace-store"); await meterEvent(tenantId, "email.sent", `${id}:${new Date().toISOString().slice(0, 16)}`);
    const row = await db.prepare("SELECT * FROM quote_recipients WHERE id=?").bind(id).first<Record<string, unknown>>(); if (row) created.push(mapRecipient(row));
  }
  return created;
}

export async function resolveRecipientToken(token: string) { const db = await ensureDelivery(); return db.prepare("SELECT id,tenant_id,quote_reference,name,email,status,signer_role,signing_order,signature_required,signed_at,expires_at FROM quote_recipients WHERE token=? AND status!='Revoked'").bind(token).first<{ id: string; tenant_id: string; quote_reference: string; name: string; email: string; status: Recipient["status"]; signer_role: RecipientRole; signing_order: number; signature_required: number; signed_at: string | null; expires_at: string | null }>(); }
export async function listDeliveryDetail(tenantId: string, reference: string) { const db = await ensureDelivery(); const recipients = await db.prepare(`SELECT r.id,r.quote_reference,r.name,r.email,r.token,r.status,r.signer_role,r.signing_order,r.signature_required,r.signed_at,r.accepted_name,r.expires_at,r.reminder_interval_days,r.next_reminder_at,r.reminder_count,r.delivered_at,r.first_viewed_at,r.last_sent_at,COUNT(CASE WHEN e.event_type='open' THEN 1 END) AS open_count,COALESCE(SUM(CASE WHEN e.event_type='section_heartbeat' THEN e.duration_ms ELSE 0 END),0) AS total_dwell,MAX(e.created_at) AS last_activity FROM quote_recipients r LEFT JOIN tracking_events e ON e.recipient_id=r.id WHERE r.tenant_id=? AND r.quote_reference=? GROUP BY r.id ORDER BY r.signing_order,r.created_at`).bind(tenantId, reference).all<Record<string, unknown>>(); const sections = await db.prepare(`SELECT section,COALESCE(SUM(duration_ms),0) AS duration_ms,COUNT(DISTINCT recipient_id) AS viewers FROM tracking_events WHERE tenant_id=? AND quote_reference=? AND event_type='section_heartbeat' GROUP BY section ORDER BY duration_ms DESC`).bind(tenantId, reference).all<Record<string, unknown>>(); return { recipients: recipients.results, sections: sections.results }; }
export async function revokeRecipient(tenantId: string, recipientId: string) { const db = await ensureDelivery(); await db.prepare("UPDATE quote_recipients SET status='Revoked',revoked_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=?").bind(tenantId, recipientId).run(); }
export async function sendRecipientReminder(tenantId: string, recipientId: string, actorEmail: string, origin: string) { const db = await ensureDelivery(); const row = await db.prepare("SELECT quote_reference,name,email,token,signer_role,signing_order,signature_required,reminder_interval_days,expires_at FROM quote_recipients WHERE tenant_id=? AND id=? AND status!='Revoked' AND signed_at IS NULL").bind(tenantId, recipientId).first<Record<string, unknown>>(); if (!row) throw new Error("Only an active unsigned recipient can be reminded."); const created = await createRecipients(tenantId, String(row.quote_reference), [{ name: String(row.name), email: String(row.email), role: row.signer_role as RecipientRole, signingOrder: Number(row.signing_order), signatureRequired: Number(row.signature_required) === 1, reminderIntervalDays: Number(row.reminder_interval_days), expiresAt: row.expires_at ? String(row.expires_at) : null }], actorEmail, origin, "Reminder: your review or signature is still required for this proposal."); await db.prepare("UPDATE quote_recipients SET reminder_count=reminder_count+1 WHERE id=?").bind(recipientId).run(); return created[0]; }
export async function recordRecipientSignature(token: string, acceptedName: string, evidence: Record<string, unknown>) {
  const db = await ensureDelivery(); const recipient = await resolveRecipientToken(token); if (!recipient) throw new Error("This signing link is invalid or revoked.");
  if (recipient.expires_at && new Date(recipient.expires_at).getTime() < Date.now()) throw new Error("This signing link has expired.");
  if (recipient.signature_required !== 1) throw new Error("This recipient is not configured as a signatory.");
  const blockers = await db.prepare("SELECT COUNT(*) AS total FROM quote_recipients WHERE tenant_id=? AND quote_reference=? AND signature_required=1 AND status!='Revoked' AND signing_order<? AND signed_at IS NULL").bind(recipient.tenant_id, recipient.quote_reference, recipient.signing_order).first<{ total: number }>();
  if (Number(blockers?.total ?? 0) > 0) throw new Error("An earlier signatory must complete signing first.");
  if (!recipient.signed_at) await db.prepare("UPDATE quote_recipients SET signed_at=CURRENT_TIMESTAMP,accepted_name=?,signature_evidence_json=? WHERE id=? AND signed_at IS NULL").bind(acceptedName, JSON.stringify(evidence), recipient.id).run();
  await recordTrackingEvent(token, "signature_recorded", null, null, null, { role: recipient.signer_role, signingOrder: recipient.signing_order });
  const remaining = await db.prepare("SELECT COUNT(*) AS total FROM quote_recipients WHERE tenant_id=? AND quote_reference=? AND signature_required=1 AND status!='Revoked' AND signed_at IS NULL").bind(recipient.tenant_id, recipient.quote_reference).first<{ total: number }>();
  const signers = await db.prepare("SELECT id,name,email,signer_role,signing_order,signed_at,signature_evidence_json FROM quote_recipients WHERE tenant_id=? AND quote_reference=? AND signature_required=1 AND status!='Revoked' ORDER BY signing_order,created_at").bind(recipient.tenant_id, recipient.quote_reference).all<Record<string, unknown>>();
  return { recipient, complete: Number(remaining?.total ?? 0) === 0, remaining: Number(remaining?.total ?? 0), signers: signers.results };
}
export async function exportRecipientEvents(tenantId: string, recipientId: string) { const db = await ensureDelivery(); const recipient = await db.prepare("SELECT id,quote_reference,name,email,status,signer_role,signing_order,signature_required,signed_at,accepted_name,expires_at,reminder_count,delivered_at,first_viewed_at,last_sent_at,created_at FROM quote_recipients WHERE tenant_id=? AND id=?").bind(tenantId, recipientId).first<Record<string, unknown>>(); if (!recipient) throw new Error("Recipient not found."); const events = await db.prepare("SELECT event_type,section,duration_ms,device_hash,coarse_location,payload_json,created_at FROM tracking_events WHERE tenant_id=? AND recipient_id=? ORDER BY created_at").bind(tenantId, recipientId).all<Record<string, unknown>>(); return { exportedAt: new Date().toISOString(), recipient, events: events.results.map((event) => ({ ...event, payload_json: JSON.parse(String(event.payload_json ?? "{}")) })) }; }
export async function deleteRecipientEvents(tenantId: string, recipientId: string, actorEmail: string) { const db = await ensureDelivery(); const recipient = await db.prepare("SELECT id,quote_reference FROM quote_recipients WHERE tenant_id=? AND id=?").bind(tenantId, recipientId).first<{ id: string; quote_reference: string }>(); if (!recipient) throw new Error("Recipient not found."); await db.prepare("DELETE FROM tracking_events WHERE tenant_id=? AND recipient_id=?").bind(tenantId, recipientId).run(); const { auditSecurity } = await import("./workspace-store"); await auditSecurity({ tenantId, actorEmail, eventType: "recipient.tracking_deleted", resourceType: "recipient", resourceId: recipientId, outcome: "success", details: { quoteReference: recipient.quote_reference } }); }
export async function recordTrackingEvent(token: string, eventType: string, section: string | null, durationMs: number | null, deviceHash: string | null, payload: Record<string, unknown>) { const db = await ensureDelivery(); const recipient = await db.prepare("SELECT r.id,r.tenant_id,r.quote_reference,r.first_viewed_at,COALESCE(t.tracking_enabled,1) AS tracking_enabled FROM quote_recipients r LEFT JOIN tenants t ON t.id=r.tenant_id WHERE r.token=? AND r.status!='Revoked'").bind(token).first<{ id: string; tenant_id: string; quote_reference: string; first_viewed_at: string | null; tracking_enabled: number }>(); if (!recipient) return null; if (recipient.tracking_enabled !== 1 && !["signature_recorded", "email_delivered", "email_queued"].includes(eventType)) return recipient; if (eventType === "open" && !recipient.first_viewed_at) await db.prepare("UPDATE quote_recipients SET first_viewed_at=CURRENT_TIMESTAMP WHERE id=?").bind(recipient.id).run(); const coarseLocation = String(payload.coarseLocation ?? "Unknown"); if (eventType === "open" && deviceHash) { const previous = await db.prepare("SELECT device_hash,coarse_location FROM tracking_events WHERE recipient_id=? AND event_type='open' AND device_hash IS NOT NULL ORDER BY created_at DESC LIMIT 1").bind(recipient.id).first<{ device_hash: string; coarse_location: string }>(); if (previous && previous.device_hash !== deviceHash) await db.prepare("INSERT INTO tracking_events (id,tenant_id,quote_reference,recipient_id,event_type,device_hash,coarse_location,payload_json) VALUES (?,?,?,?,'possible_forward',?,?,?)").bind(crypto.randomUUID(), recipient.tenant_id, recipient.quote_reference, recipient.id, deviceHash, coarseLocation, JSON.stringify({ previousDeviceHash: previous.device_hash, previousLocation: previous.coarse_location })).run(); } await db.prepare("INSERT INTO tracking_events (id,tenant_id,quote_reference,recipient_id,event_type,section,duration_ms,device_hash,coarse_location,payload_json) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(), recipient.tenant_id, recipient.quote_reference, recipient.id, eventType, section, durationMs, deviceHash, coarseLocation, JSON.stringify(payload)).run(); return recipient; }
