const KEY_SCHEMA = `CREATE TABLE IF NOT EXISTS api_keys (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, name TEXT NOT NULL, prefix TEXT NOT NULL, key_hash TEXT NOT NULL UNIQUE, scopes_json TEXT NOT NULL, revoked_at TEXT, last_used_at TEXT, created_by TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`;
const ENDPOINT_SCHEMA = `CREATE TABLE IF NOT EXISTS webhook_endpoints (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, name TEXT NOT NULL, url TEXT NOT NULL, secret TEXT NOT NULL, events_json TEXT NOT NULL, include_monetary INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL, failure_started_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`;
const DELIVERY_SCHEMA = `CREATE TABLE IF NOT EXISTS webhook_deliveries (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, endpoint_id TEXT NOT NULL, event_type TEXT NOT NULL, payload_json TEXT NOT NULL, status TEXT NOT NULL, attempt_count INTEGER NOT NULL DEFAULT 0, response_status INTEGER, response_body TEXT, next_retry_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`;
const ACCESS_SCHEMA = `CREATE TABLE IF NOT EXISTS api_access_log (id TEXT PRIMARY KEY, tenant_id TEXT, key_prefix TEXT, resource TEXT NOT NULL, outcome TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`;
const EVENTS = ["quote.sent", "quote.first_viewed", "quote.accepted", "quote.declined"];
async function database() { const { env } = await import("cloudflare:workers"); if (!env.DB) throw new Error("Integration storage is unavailable."); return env.DB; }
async function ensure() { const db = await database(); await db.batch([db.prepare(KEY_SCHEMA), db.prepare(ENDPOINT_SCHEMA), db.prepare(DELIVERY_SCHEMA), db.prepare(ACCESS_SCHEMA), db.prepare("CREATE INDEX IF NOT EXISTS api_keys_tenant_idx ON api_keys (tenant_id)"), db.prepare("CREATE INDEX IF NOT EXISTS webhook_endpoints_tenant_idx ON webhook_endpoints (tenant_id)"), db.prepare("CREATE INDEX IF NOT EXISTS webhook_deliveries_tenant_idx ON webhook_deliveries (tenant_id, created_at)")]); return db; }
async function digest(value: string) { const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return Array.from(new Uint8Array(bytes), (byte) => byte.toString(16).padStart(2, "0")).join(""); }
async function sign(secret: string, value: string) { const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const bytes = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(value)); return Array.from(new Uint8Array(bytes), (byte) => byte.toString(16).padStart(2, "0")).join(""); }
export async function getIntegrationWorkspace(tenantId: string) { const db = await ensure(); const [keys, endpoints, deliveries] = await Promise.all([db.prepare("SELECT id,name,prefix,scopes_json,revoked_at,last_used_at,created_at FROM api_keys WHERE tenant_id=? ORDER BY created_at DESC").bind(tenantId).all<Record<string,unknown>>(), db.prepare("SELECT id,name,url,events_json,include_monetary,status,failure_started_at,created_at FROM webhook_endpoints WHERE tenant_id=? ORDER BY created_at DESC").bind(tenantId).all<Record<string,unknown>>(), db.prepare("SELECT d.id,d.event_type,d.status,d.attempt_count,d.response_status,d.response_body,d.next_retry_at,d.created_at,e.name AS endpoint_name FROM webhook_deliveries d JOIN webhook_endpoints e ON e.id=d.endpoint_id WHERE d.tenant_id=? ORDER BY d.created_at DESC LIMIT 50").bind(tenantId).all<Record<string,unknown>>()]); return { keys: keys.results.map((row) => ({ ...row, scopes: JSON.parse(String(row.scopes_json)) })), endpoints: endpoints.results.map((row) => ({ ...row, events: JSON.parse(String(row.events_json)), includeMonetary: row.include_monetary === 1 })), deliveries: deliveries.results, supportedEvents: EVENTS }; }
export async function createApiKey(tenantId: string, name: string, scopes: string[], actor: string) { const allowed = scopes.filter((scope) => ["clients:read","catalogue:read","quotes:read"].includes(scope)); if (!name.trim() || !allowed.length) throw new Error("A key name and at least one read scope are required."); const raw = `qb_live_${crypto.randomUUID().replaceAll("-","")}${crypto.randomUUID().replaceAll("-","")}`; const prefix = raw.slice(0, 15); const db = await ensure(); await db.prepare("INSERT INTO api_keys (id,tenant_id,name,prefix,key_hash,scopes_json,created_by) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(), tenantId, name.trim(), prefix, await digest(raw), JSON.stringify(allowed), actor).run(); return { raw, workspace: await getIntegrationWorkspace(tenantId) }; }
export async function revokeApiKey(tenantId: string, id: string) { const db = await ensure(); await db.prepare("UPDATE api_keys SET revoked_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=?").bind(tenantId,id).run(); return getIntegrationWorkspace(tenantId); }
export async function authenticateApiKey(raw: string | null, resource: string) { const db = await ensure(); const prefix = raw?.slice(0,15) ?? null; const hash = raw ? await digest(raw) : ""; const row = raw ? await db.prepare("SELECT id,tenant_id,scopes_json,revoked_at FROM api_keys WHERE key_hash=?").bind(hash).first<{id:string;tenant_id:string;scopes_json:string;revoked_at:string|null}>() : null; const scope = `${resource}:read`; const outcome = !row ? "unauthorised" : row.revoked_at ? "revoked_key" : !(JSON.parse(row.scopes_json) as string[]).includes(scope) ? "insufficient_scope" : "authorised"; await db.prepare("INSERT INTO api_access_log (id,tenant_id,key_prefix,resource,outcome) VALUES (?,?,?,?,?)").bind(crypto.randomUUID(), row?.tenant_id ?? null, prefix, resource, outcome).run(); if (outcome !== "authorised" || !row) return null; await db.prepare("UPDATE api_keys SET last_used_at=CURRENT_TIMESTAMP WHERE id=?").bind(row.id).run(); return { tenantId: row.tenant_id, keyId: row.id, prefix: prefix ?? "unknown" }; }
export function assertSafeWebhookUrl(value:string) {
  if (!value || value.length > 2048) throw new Error("Webhook endpoint is invalid.");
  let url: URL;
  try { url = new URL(value); } catch { throw new Error("Webhook endpoint is invalid."); }
  if (url.protocol !== "https:") throw new Error("Webhook endpoints must use HTTPS.");
  if (url.username || url.password) throw new Error("Webhook endpoints cannot include credentials.");
  if (url.port && url.port !== "443") throw new Error("Webhook endpoints must use the standard HTTPS port.");
  const hostname = url.hostname.toLowerCase().replace(/^\[|\]$/g, "");
  if (!hostname || hostname.length > 253 || hostname === "localhost" || hostname.endsWith(".localhost") || hostname.endsWith(".local") || hostname.endsWith(".internal")) throw new Error("Webhook endpoints must use a public hostname.");
  if (hostname.includes(":")) throw new Error("Literal IPv6 webhook destinations are not supported.");
  const ipv4 = hostname.match(/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/)?.slice(1).map(Number);
  if (ipv4) {
    if (ipv4.some((part) => part > 255)) throw new Error("Webhook endpoint is invalid.");
    const [a,b] = ipv4;
    if (a === 0 || a === 10 || a === 127 || a >= 224 || (a === 100 && b >= 64 && b <= 127) || (a === 169 && b === 254) || (a === 172 && b >= 16 && b <= 31) || (a === 192 && b === 168)) throw new Error("Webhook endpoints must not target private or reserved networks.");
  } else if (!hostname.includes(".")) {
    throw new Error("Webhook endpoints must use a fully qualified public hostname.");
  }
  return url.toString();
}
export async function createWebhook(tenantId:string,input:{name:string;url:string;events:string[];includeMonetary:boolean}) { const safeUrl = assertSafeWebhookUrl(input.url); const events = input.events.filter((event) => EVENTS.includes(event)); if (!input.name.trim() || !events.length) throw new Error("A webhook name and event are required."); const secret=`whsec_${crypto.randomUUID().replaceAll("-","")}`; const db=await ensure(); await db.prepare("INSERT INTO webhook_endpoints (id,tenant_id,name,url,secret,events_json,include_monetary,status) VALUES (?,?,?,?,?,?,?,'Active')").bind(crypto.randomUUID(),tenantId,input.name.trim(),safeUrl,secret,JSON.stringify(events),input.includeMonetary?1:0).run(); return { secret, workspace: await getIntegrationWorkspace(tenantId) }; }
export async function disableWebhook(tenantId:string,id:string) { const db=await ensure(); await db.prepare("UPDATE webhook_endpoints SET status='Disabled',updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=?").bind(tenantId,id).run(); return getIntegrationWorkspace(tenantId); }
async function deliver(endpoint:{id:string;tenant_id:string;url:string;secret:string}, eventType:string, payload:Record<string,unknown>) { const db=await ensure(); const deliveryId=crypto.randomUUID(); const body=JSON.stringify(payload); const signature=await sign(endpoint.secret,body); let status="Failed",responseStatus:number|null=null,responseBody=""; try { const safeUrl=assertSafeWebhookUrl(endpoint.url); const response=await fetch(safeUrl,{method:"POST",headers:{"content-type":"application/json","x-quotebench-event":eventType,"x-quotebench-signature":`sha256=${signature}`},body,redirect:"manual",signal:AbortSignal.timeout(6000)}); responseStatus=response.status; responseBody=(await response.text()).slice(0,1000); status=response.ok?"Delivered":"Retrying"; } catch(error) { responseBody=error instanceof Error?error.message:"Network error"; status="Retrying"; } await db.prepare("INSERT INTO webhook_deliveries (id,tenant_id,endpoint_id,event_type,payload_json,status,attempt_count,response_status,response_body,next_retry_at) VALUES (?,?,?,?,?,?,1,?,?,CASE WHEN ?='Retrying' THEN datetime('now','+5 minutes') ELSE NULL END)").bind(deliveryId,endpoint.tenant_id,endpoint.id,eventType,body,status,responseStatus,responseBody,status).run(); if(status==="Retrying") await db.prepare("UPDATE webhook_endpoints SET failure_started_at=COALESCE(failure_started_at,CURRENT_TIMESTAMP),updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(endpoint.id).run(); else await db.prepare("UPDATE webhook_endpoints SET failure_started_at=NULL WHERE id=?").bind(endpoint.id).run(); return deliveryId; }
export async function emitWebhooks(tenantId:string,eventType:string,data:Record<string,unknown>) { const db=await ensure(); const endpoints=await db.prepare("SELECT id,tenant_id,url,secret,events_json,include_monetary FROM webhook_endpoints WHERE tenant_id=? AND status='Active'").bind(tenantId).all<{id:string;tenant_id:string;url:string;secret:string;events_json:string;include_monetary:number}>(); const recent=await db.prepare("SELECT COUNT(*) AS count FROM webhook_deliveries WHERE tenant_id=? AND created_at>datetime('now','-1 minute')").bind(tenantId).first<{count:number}>(); if((recent?.count??0)>=60)return; for(const endpoint of endpoints.results) { if(!(JSON.parse(endpoint.events_json) as string[]).includes(eventType))continue; const filtered=endpoint.include_monetary===1?data:Object.fromEntries(Object.entries(data).filter(([key])=>!/amount|price|total|margin|value/i.test(key))); await deliver(endpoint,eventType,{id:crypto.randomUUID(),type:eventType,occurredAt:new Date().toISOString(),data:filtered}); } }
export async function sendTestWebhook(tenantId:string,id:string) { const db=await ensure(); const endpoint=await db.prepare("SELECT id,tenant_id,url,secret FROM webhook_endpoints WHERE tenant_id=? AND id=? AND status='Active'").bind(tenantId,id).first<{id:string;tenant_id:string;url:string;secret:string}>(); if(!endpoint)throw new Error("Active webhook endpoint not found."); await deliver(endpoint,"test",{id:crypto.randomUUID(),type:"test",occurredAt:new Date().toISOString(),data:{message:"QuoteBench webhook verification"}}); return getIntegrationWorkspace(tenantId); }

export async function processDueWebhookRetries() {
  const db = await ensure();
  const due = await db.prepare(`SELECT d.id,d.tenant_id,d.endpoint_id,d.event_type,d.payload_json,d.attempt_count,e.url,e.secret,e.failure_started_at
    FROM webhook_deliveries d JOIN webhook_endpoints e ON e.id=d.endpoint_id
    WHERE d.status='Retrying' AND d.next_retry_at<=CURRENT_TIMESTAMP AND e.status='Active'
    ORDER BY d.next_retry_at LIMIT 50`).all<{id:string;tenant_id:string;endpoint_id:string;event_type:string;payload_json:string;attempt_count:number;url:string;secret:string;failure_started_at:string|null}>();
  let delivered = 0; let disabled = 0;
  for (const item of due.results) {
    const body = item.payload_json; const signature = await sign(item.secret, body); let ok = false; let responseStatus: number | null = null; let responseBody = "";
    try { const safeUrl=assertSafeWebhookUrl(item.url); const response = await fetch(safeUrl, { method: "POST", headers: { "content-type": "application/json", "x-quotebench-event": item.event_type, "x-quotebench-signature": `sha256=${signature}` }, body, redirect: "manual", signal: AbortSignal.timeout(6000) }); responseStatus = response.status; responseBody = (await response.text()).slice(0, 1000); ok = response.ok; } catch (error) { responseBody = error instanceof Error ? error.message : "Network error"; }
    const attempt = item.attempt_count + 1;
    const failureStarted = item.failure_started_at ? new Date(`${item.failure_started_at.replace(" ", "T")}Z`).getTime() : Date.now();
    const stale = Date.now() - failureStarted >= 24 * 60 * 60 * 1000;
    if (ok) { delivered += 1; await db.batch([db.prepare("UPDATE webhook_deliveries SET status='Delivered',attempt_count=?,response_status=?,response_body=?,next_retry_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(attempt,responseStatus,responseBody,item.id),db.prepare("UPDATE webhook_endpoints SET failure_started_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(item.endpoint_id)]); }
    else if (stale) { disabled += 1; await db.batch([db.prepare("UPDATE webhook_deliveries SET status='Failed',attempt_count=?,response_status=?,response_body=?,next_retry_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(attempt,responseStatus,responseBody,item.id),db.prepare("UPDATE webhook_endpoints SET status='Disabled',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(item.endpoint_id)]); }
    else { const delay = Math.min(360, 5 * 2 ** Math.min(attempt - 1, 6)); await db.prepare("UPDATE webhook_deliveries SET attempt_count=?,response_status=?,response_body=?,next_retry_at=datetime('now',?),updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(attempt,responseStatus,responseBody,`+${delay} minutes`,item.id).run(); }
  }
  return { processed: due.results.length, delivered, disabled };
}
