import { getDatabase } from "./database.ts";
import { headers } from "next/headers";
import type { QuoteBenchUser } from "../app/auth";
import type { WorkspaceRole } from "./member-store";

const TENANT_SCHEMA=`CREATE TABLE IF NOT EXISTS tenants (id TEXT PRIMARY KEY,name TEXT NOT NULL,currency TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Active',tracking_enabled INTEGER NOT NULL DEFAULT 1,deleted_at TEXT,purge_after TEXT,billing_anniversary_day INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`;
const SECURITY_SCHEMA=`CREATE TABLE IF NOT EXISTS security_events (id TEXT PRIMARY KEY,tenant_id TEXT,actor_email TEXT,event_type TEXT NOT NULL,resource_type TEXT,resource_id TEXT,outcome TEXT NOT NULL,details_json TEXT NOT NULL DEFAULT '{}',request_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`;
const METER_SCHEMA=`CREATE TABLE IF NOT EXISTS metered_events (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,metric TEXT NOT NULL,quantity INTEGER NOT NULL DEFAULT 1,source_id TEXT NOT NULL,occurred_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`;
const RATE_SCHEMA=`CREATE TABLE IF NOT EXISTS rate_limits (bucket_key TEXT PRIMARY KEY,window_started_at TEXT NOT NULL,count INTEGER NOT NULL,expires_at TEXT NOT NULL)`;
const MEMBER_SCHEMA=`CREATE TABLE IF NOT EXISTS workspace_members (tenant_id TEXT NOT NULL,email TEXT NOT NULL,display_name TEXT NOT NULL,role TEXT NOT NULL,status TEXT NOT NULL,invited_by TEXT,invited_at TEXT,expires_at TEXT,joined_at TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (tenant_id,email))`;
async function database(){return getDatabase("Workspace storage is unavailable.");}
async function ensure(){const db=await database();await db.batch([db.prepare(TENANT_SCHEMA),db.prepare(SECURITY_SCHEMA),db.prepare(METER_SCHEMA),db.prepare(RATE_SCHEMA),db.prepare(MEMBER_SCHEMA),db.prepare("CREATE INDEX IF NOT EXISTS security_events_tenant_created_idx ON security_events (tenant_id,created_at)"),db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS metered_events_tenant_metric_source_unique ON metered_events (tenant_id,metric,source_id)"),db.prepare("CREATE INDEX IF NOT EXISTS metered_events_tenant_time_idx ON metered_events (tenant_id,occurred_at)")]);try{await db.prepare("SELECT tracking_enabled FROM tenants LIMIT 0").run();}catch{await db.prepare("ALTER TABLE tenants ADD COLUMN tracking_enabled INTEGER NOT NULL DEFAULT 1").run();}await db.prepare("INSERT OR IGNORE INTO tenants (id,name,currency,billing_anniversary_day) VALUES ('finance-advisory-partners','Finance Advisory Partners','GBP',1)").run();return db;}
function workspaceName(user:QuoteBenchUser){const base=(user.fullName??user.displayName??user.email.split("@")[0]).trim();return `${base}'s workspace`.slice(0,120);}
async function createTenantForUser(user:QuoteBenchUser){const db=await ensure();const tenantId=`ws_${crypto.randomUUID().replaceAll("-","")}`;await db.batch([db.prepare("INSERT INTO tenants (id,name,currency,billing_anniversary_day) VALUES (?,?, 'GBP',?)").bind(tenantId,workspaceName(user),new Date().getUTCDate()),db.prepare("INSERT INTO workspace_members (tenant_id,email,display_name,role,status,joined_at) VALUES (?,?,?,'owner','Active',CURRENT_TIMESTAMP)").bind(tenantId,user.email.toLowerCase(),user.displayName)]);return tenantId;}
export async function auditSecurity(input:{tenantId?:string|null;actorEmail?:string|null;eventType:string;resourceType?:string;resourceId?:string;outcome:string;details?:Record<string,unknown>;requestId?:string|null}){const db=await ensure();await db.prepare("INSERT INTO security_events (id,tenant_id,actor_email,event_type,resource_type,resource_id,outcome,details_json,request_id) VALUES (?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),input.tenantId??null,input.actorEmail?.toLowerCase()??null,input.eventType,input.resourceType??null,input.resourceId??null,input.outcome,JSON.stringify(input.details??{}),input.requestId??null).run();}
export async function requireWorkspaceContext(user:QuoteBenchUser,allowed:WorkspaceRole[]){const db=await ensure();const requestHeaders=await headers();const requested=requestHeaders.get("x-quotebench-workspace")??requestHeaders.get("cookie")?.match(/(?:^|;\s*)qb-workspace=([^;]+)/)?.[1]??null;let memberships=await db.prepare("SELECT m.tenant_id,m.role,m.status,t.name,t.currency FROM workspace_members m JOIN tenants t ON t.id=m.tenant_id WHERE m.email=? AND m.status='Active' AND t.status='Active' ORDER BY m.joined_at,m.tenant_id").bind(user.email.toLowerCase()).all<{tenant_id:string;role:WorkspaceRole;status:string;name:string;currency:string}>();if(!memberships.results.length){const tenantId=await createTenantForUser(user);memberships=await db.prepare("SELECT m.tenant_id,m.role,m.status,t.name,t.currency FROM workspace_members m JOIN tenants t ON t.id=m.tenant_id WHERE m.email=? AND m.status='Active'").bind(user.email.toLowerCase()).all();if(!memberships.results.length)throw new Error("workspace_initialisation_failed");const member=memberships.results[0] as {tenant_id:string;role:WorkspaceRole;name:string;currency:string};return{tenantId,role:member.role,workspaceName:member.name,currency:member.currency};}const selected=requested?memberships.results.find(row=>row.tenant_id===requested):memberships.results[0];if(!selected){await auditSecurity({tenantId:requested,actorEmail:user.email,eventType:"tenant.boundary_denied",outcome:"denied",details:{requestedTenantId:requested}});throw new Error("forbidden: workspace membership required");}if(!allowed.includes(selected.role)){await auditSecurity({tenantId:selected.tenant_id,actorEmail:user.email,eventType:"authorisation.denied",outcome:"denied",details:{actualRole:selected.role,allowed}});throw new Error(`forbidden: this action requires ${allowed.join(" or ")} role`);}return{tenantId:selected.tenant_id,role:selected.role,workspaceName:selected.name,currency:selected.currency};}
export async function listUserWorkspaces(user:QuoteBenchUser){const db=await ensure();const rows=await db.prepare("SELECT t.id,t.name,t.currency,m.role FROM workspace_members m JOIN tenants t ON t.id=m.tenant_id WHERE m.email=? AND m.status='Active' AND t.status='Active' ORDER BY t.name").bind(user.email.toLowerCase()).all<Record<string,unknown>>();return rows.results;}
export async function meterEvent(tenantId:string,metric:string,sourceId:string,quantity=1){const db=await ensure();await db.prepare("INSERT OR IGNORE INTO metered_events (id,tenant_id,metric,quantity,source_id) VALUES (?,?,?,?,?)").bind(crypto.randomUUID(),tenantId,metric,quantity,sourceId).run();}
export async function enforceRateLimit(bucketKey:string,limit:number,windowSeconds:number){const db=await ensure();const interval=`+${windowSeconds} seconds`;const row=await db.prepare(`INSERT INTO rate_limits (bucket_key,window_started_at,count,expires_at) VALUES (?,CURRENT_TIMESTAMP,1,datetime('now',?)) ON CONFLICT(bucket_key) DO UPDATE SET window_started_at=CASE WHEN rate_limits.expires_at<=CURRENT_TIMESTAMP THEN CURRENT_TIMESTAMP ELSE rate_limits.window_started_at END,count=CASE WHEN rate_limits.expires_at<=CURRENT_TIMESTAMP THEN 1 ELSE rate_limits.count+1 END,expires_at=CASE WHEN rate_limits.expires_at<=CURRENT_TIMESTAMP THEN datetime('now',?) ELSE rate_limits.expires_at END RETURNING count,expires_at`).bind(bucketKey,interval,interval).first<{count:number;expires_at:string}>();if(!row)throw new Error("Rate limit storage is unavailable.");const allowed=row.count<=limit;return{allowed,remaining:allowed?Math.max(0,limit-row.count):0,resetAt:new Date(`${row.expires_at.replace(" ","T")}Z`).toISOString()};}
export async function enforceTokenRateLimit(token:string,action:string,limit:number,windowSeconds=60){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token));const hash=Array.from(new Uint8Array(bytes),byte=>byte.toString(16).padStart(2,"0")).join("");return enforceRateLimit(`public:${action}:${hash}`,limit,windowSeconds);}
export async function softDeleteTenant(tenantId:string,actorEmail:string,confirmation:string){const db=await ensure();const tenant=await db.prepare("SELECT name FROM tenants WHERE id=? AND status='Active'").bind(tenantId).first<{name:string}>();if(!tenant||confirmation!==tenant.name)throw new Error("workspace_name_confirmation_required");await db.prepare("UPDATE tenants SET status='SoftDeleted',deleted_at=CURRENT_TIMESTAMP,purge_after=datetime('now','+30 days'),updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(tenantId).run();await auditSecurity({tenantId,actorEmail,eventType:"tenant.soft_deleted",outcome:"success",details:{purgeAfterDays:30}});}
export async function getGovernanceWorkspace(tenantId:string){const db=await ensure();const [tenant,events]=await Promise.all([db.prepare("SELECT name,currency,status,tracking_enabled,deleted_at,purge_after,created_at FROM tenants WHERE id=?").bind(tenantId).first<Record<string,unknown>>(),db.prepare("SELECT id,actor_email,event_type,resource_type,resource_id,outcome,details_json,request_id,created_at FROM security_events WHERE tenant_id=? ORDER BY created_at DESC LIMIT 100").bind(tenantId).all<Record<string,unknown>>()]);return{tenant:{...tenant,trackingEnabled:tenant?.tracking_enabled===1},securityEvents:events.results.map(event=>({...event,details:JSON.parse(String(event.details_json??"{}"))})),retention:{trackingMonths:24,webhookLogDays:30,apiAccessLogDays:90,softDeleteDays:30}};}
export async function setTrackingEnabled(tenantId:string,actorEmail:string,enabled:boolean){const db=await ensure();await db.prepare("UPDATE tenants SET tracking_enabled=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='Active'").bind(enabled?1:0,tenantId).run();await auditSecurity({tenantId,actorEmail,eventType:"tracking.preference_changed",resourceType:"tenant",resourceId:tenantId,outcome:"success",details:{enabled}});return getGovernanceWorkspace(tenantId);}
export async function hasOperatorAccess(user:QuoteBenchUser){const{env}=await import("cloudflare:workers");const configured=String(env.OPERATOR_EMAIL_SHA256??"").split(",").map(value=>value.trim().toLowerCase()).filter(value=>/^[a-f0-9]{64}$/.test(value));const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(user.email.trim().toLowerCase()));const candidate=Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,"0")).join("");return configured.some(value=>value===candidate);}
export async function requireOperator(user:QuoteBenchUser){if(!await hasOperatorAccess(user)){await auditSecurity({actorEmail:user.email,eventType:"operator.access_denied",outcome:"denied"});throw new Error("forbidden: platform operator access required");}return user;}
